# Generated by Django 5.2.1 on 2025-05-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('bill_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('yarn_lot', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('yarn_count', models.CharField(max_length=50)),
                ('no_of_cones', models.PositiveIntegerField()),
                ('avg_cone_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, editable=False, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Production_Issued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('bill_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('yarn_lot', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('yarn_count', models.CharField(max_length=50)),
                ('no_of_cones', models.PositiveIntegerField()),
                ('avg_cone_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, editable=False, max_digits=10, null=True)),
                ('article', models.CharField(max_length=50)),
                ('no_of_article', models.PositiveIntegerField()),
                ('average_weight_of_article', models.DecimalField(decimal_places=3, max_digits=10)),
                ('required_weight_for_prod', models.DecimalField(decimal_places=3, editable=False, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Production_Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('bill_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('yarn_lot', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('yarn_count', models.CharField(max_length=50)),
                ('no_of_cones', models.PositiveIntegerField()),
                ('avg_cone_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, editable=False, max_digits=10, null=True)),
                ('article', models.CharField(blank=True, editable=False, max_length=50)),
                ('no_of_article', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('average_weight_of_article', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=10, null=True)),
                ('required_weight_for_prod', models.DecimalField(decimal_places=3, editable=False, max_digits=10, null=True)),
                ('yarn_wastage', models.DecimalField(decimal_places=3, editable=False, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('bill_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('yarn_lot', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('yarn_count', models.CharField(max_length=50)),
                ('no_of_cones', models.PositiveIntegerField()),
                ('avg_cone_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, editable=False, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
