# Generated by Django 5.2.1 on 2025-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued',
            name='colour',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='production_issued',
            name='colour',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='production_return',
            name='colour',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='colour',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issued',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='production_issued',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='production_return',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
