# Generated by Django 5.2.1 on 2025-05-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_issued_remarks_alter_production_issued_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_return',
            name='total_usage',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='production_return',
            name='colour',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='production_return',
            name='content',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='production_return',
            name='name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='production_return',
            name='yarn_count',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='production_return',
            name='yarn_lot',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
