# Generated by Django 5.2.1 on 2025-05-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_production_return_total_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production_return',
            name='no_of_returned_article',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='production_return',
            name='weight_of_returned_article',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
