# Generated by Django 5.2.1 on 2025-05-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_production_return_no_of_returned_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='production_issued',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='production_return',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=6, null=True),
        ),
    ]
