# Generated by Django 5.2.1 on 2025-05-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_issued_net_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='Receipt_type',
            field=models.CharField(choices=[('IM', 'Imported'), ('Lo', 'Local')], default='', max_length=50, null=True),
        ),
    ]
