# Generated by Django 5.2.1 on 2025-05-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_receipt_receipt_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='Receipt_type',
            new_name='receipt_type',
        ),
    ]
