# Generated by Django 5.2.1 on 2025-05-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_rename_receipt_type_receipt_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(choices=[('Local', 'LO'), ('Imported', 'IM')], default='', max_length=50, null=True),
        ),
    ]
